ninety-nine-cats/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cats, except: :destroy
  root "cats#index"

end

ninety-nine-cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ninety-nine-cats/app/models/cat.rb
require 'action_view'
require 'date'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS = ['red', 'green', 'blue']

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: { in: CAT_COLORS}
    validates :sex, inclusion: { in: %w(M F)}
    validate :birth_date_cannot_be_future

    def birth_date_cannot_be_future
        if birth_date.present? && birth_date > Date.today
            errors.add(birth_date, "can't be in the future")
        end
    end

    def age
        Date.today.year - birth_date.year
    end

end

ninety-nine-cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety-nine-cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end
    
    def create
        @c = Cat.new(cat_params)
        if c.save
            redirect_to cat_url(@c)
        else
            render json: c.errors.full_messages, status: 422
            # render :new
        end
    end

    def new
        render :new
    end

    def edit
        @c = Cat.find_by(id: params[:id])
        render :edit
    end

    def show
        @c = Cat.find_by(id: params[:id])
        render :show
    end

    def update
        @c = Cat.find_by(id: params[:id])
        if @c.update(cat_params)
            redirect_to cat_url(@c)
        else
            render json: @c.errors.full_messages, status: 422
            # render :edit
        end
        # render :new
    end

    private
    def cat_params
        params.require(:cat).permit(:date, :color, :name, :sex, :description)
    end
end

ninety-nine-cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety-nine-cats/app/views/cats/_form.html.erb
<form action=<% action_url == :edit ? cat_url(c) : cats_url %>  method='POST' >
    <% if action_url == :edit %>
        <input type='hidden' name='_method' value='PATCH'> 
    <% end %>
    <label>Name:
    
        <input type="text" name="cat[name]" value="<%= c.name %>">
    </label>
    <br>
    <label>Birthdate:
        <input type="date" name="cat[birth_date]"
            value="<%= c.birth_date %>">
    </label>
     <!-- <input type="text" name="cat[color]" value=""> -->
     <br>
    <label> Color: </label>
    <select> 
        <option value="<%= c.color %>" disabled > -- select a color -- </option>
        <% Cat::CAT_COLORS.each do |color| %>
            <option value="<%= color %>" <% "selected" if c.color == color%>> <%= color %></option>
        <% end %>
    </select>
    <br>
    <label>Sex:
        <% selected = c.sex == 'M' %>
        <input type="radio" name="cat[sex]" value="M" <%= "checked" if selected%>> Male
        <input type="radio" name="cat[sex]" value="F" <%= "checked" unless selected%>> Female
    </label>
    <br>
    <label>Description:
        <textarea type="text" name="cat[description]" value="<%= c.description %>"></textarea>
    </label>
</form>

ninety-nine-cats/app/views/cats/edit.html.erb
<h1> Edit Cat </h1>
<%= render 'form', c: @c, , action_url: :edit %>

ninety-nine-cats/app/views/cats/index.html.erb
<h1> Cat Index Page </h1>
<ul> 
    <%@cats.each do |cat|%>
    <a href= "<%= cat_url(cat) %>"> Cat Show Page </a>

    <li> Name: <%= cat.name %> </li>
    <li> Birthdate: <%= cat.birth_date %> </li>
    <li> Color: <%= cat.color %> </li>
    <li> Sex: <%= cat.sex %> </li>
    <li> Description: <%= cat.description %> </li>

    <% end %>
</ul>

ninety-nine-cats/app/views/cats/new.html.erb
<h1>New Cat</h1>
<% @placeholder_cat = Cat.new(birth_date: "1-1-2020", name: '', sex: 'M', color: 'green')%>
<%= render 'form', c: @placeholder_cat, action_url: :new %>

ninety-nine-cats/app/views/cats/show.html.erb
<h1> Cat Show Page </h1>

<a href= "<%= cats_url %>"> Cat Index Page </a>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th><%= @c.name %></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>Birthdate</td>
            <td><%= @c.birth_date %></td>
        </tr>

        <tr>
            <td>Color</td>
            <td><%= @c.color %></td>
        </tr>

        <tr>
            <td>Sex</td>
            <td><%= @c.sex %></td>
        </tr>

        <tr>
            <td>Description</td>
            <td><%= @c.description %></td>
        </tr>
    </tbody>
        
</table>

ninety-nine-cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>